"""empty message

Revision ID: b973507bf5e8
Revises: c7cbdeae334a
Create Date: 2023-05-17 15:18:43.691745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b973507bf5e8'
down_revision = 'c7cbdeae334a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
