"""empty message

Revision ID: c7cbdeae334a
Revises: f1d08dd46a45
Create Date: 2023-05-17 15:07:18.546514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cbdeae334a'
down_revision = 'f1d08dd46a45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('mbti', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'mbti')
    # ### end Alembic commands ###
